<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>br.usp.agv</groupId>
        <artifactId>agv-system</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>infra</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>br.usp.agv</groupId>
            <artifactId>agv-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>br.usp.agv</groupId>
            <artifactId>agv-adapters</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <!-- JAR Completo (Gerenciador do Sistema) -->
                    <execution>
                        <id>agv-system-all</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/agv-system-all.jar</outputFile>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>br.usp.agv.bootstrap.AgvSystemManager</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                    <!-- JAR para o Nó AGV -->
                    <execution>
                        <id>agv-node</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/agv-node.jar</outputFile>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>br.usp.agv.bootstrap.AgvNodeMain</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                    <!-- JAR para o Visualizador -->
                    <execution>
                        <id>visualizer</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/visualizer.jar</outputFile>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>br.usp.agv.bootstrap.VisualizerMain</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                    <!-- JAR para o Gerador de Pedidos -->
                    <execution>
                        <id>generator</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/generator.jar</outputFile>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>br.usp.agv.bootstrap.OrderGeneratorMain</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
